name: Send Report

on:
    schedule:
        # every day at 0700 ET
        - cron: '0 11 * * *'
    workflow_dispatch:

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run report
              run: python src/main.py
              env:
                MAIL_DEFAULT_SENDER: ${{ secrets.MAIL_DEFAULT_SENDER }}
                MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
                MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
                MAIL_PORT: ${{ secrets.MAIL_PORT }}
                MAIL_RECIPIENTS: ${{ secrets.MAIL_RECIPIENTS }}
                MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
